#include<iostream.h>
#include<conio.h>

void main(){
	clrscr();
	float ,b,s,r,p,d;

	//ingreso de datos
	cout<<"primer valor : ";
	cin>>a;
	cout<<"segundo valor : ";
	cin>>b;

	//realizar  calculos
	s=a+b;
	r=a-b;
	p=a*b;
	d=a/b;
	//mostrar datos
    cout<<"el resultado de la suma es: "<<s<<"\n";
    cout<<"el resultado de la resta es: "<<r<<"\n";
    cout<<"el resultado de la multiplicacion es: "<<p<<"\n";
    cout<<"el resultado de la divicion es: "<<d<<"\n";

    getch(); 
  }