#include<iostream.h>
#include <conio.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

void main(){
	clrscr();
	cout<<"Hola mundo";
	textcolor(3);
	gotoxy(30,2);
	cprintf("Hola mundo");
        gotoxy(30,3);
        cprintf("Como has estado");
        gotoxy(30,4);
        cprintf("Espero que bien la verdad");
        gotoxy(30,5);
        cprintf("Geniallll la verdad XD");
	getch();
	system("cls");
}
